### ISSUE TITLE
When/how are these reports regenerated?

### ISSUE THREAD

**Issue by akurtakov** [merks/simrel-maven#2]
I'm looking at https://github.com/merks/simrel-maven/blob/main/platform/REPORT.md and mockito is smth that I've updated to 5.0 but the report is not changing thus I wondered is this static report or autogenerated?

**Comment by merks** [comment]
Sorry, it is generated but not automated.  The commons-jxpath dependency is problematic because it depends on really old Orbit stuff in order to resolve and I don't want such dependencies in a "merged" target...

In any case, it's been regenerated and up-to-date now.  Automating that is on the todo list.

**Comment by merks** [comment]
Just ask here and I will do it...

**Comment by merks** [comment]
@akurtakov 

The minor updates list has been regenerated to just this just now:

## Minor Updates
 - [com.fasterxml.jackson.core](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/)
    - [jackson-annotations](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/) **[2.14.1](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.14.1)** < [2.14.2](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.14.2/)
    - [jackson-core](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/) **[2.14.1](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.1)** < [2.14.2](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.2/)
    - [jackson-databind](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/) **[2.14.1](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.14.1)** < [2.14.2](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.14.2/)
 - [org.apache.felix](https://repo1.maven.org/maven2/org/apache/felix/)
    - [org.apache.felix.scr](https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.scr/) **[2.2.4](https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.scr/2.2.4)** < [2.2.6](https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.scr/2.2.6/)

**Comment by akurtakov** [comment]
I'm already taking care of jackson https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/831 and will look at felix.scr shortly after that.

**Comment by akurtakov** [comment]
Would you please regen platform one?

**Comment by merks** [comment]
Just this now:

## Minor Updates
 - [org.mockito](https://repo1.maven.org/maven2/org/mockito/)
    - [mockito-core](https://repo1.maven.org/maven2/org/mockito/mockito-core/) **[5.0.0](https://repo1.maven.org/maven2/org/mockito/mockito-core/5.0.0)** < [5.1.1](https://repo1.maven.org/maven2/org/mockito/mockito-core/5.1.1/)

**Comment by akurtakov** [comment]
So nice to see clean report https://github.com/merks/simrel-maven/blob/main/platform/REPORT.md

**Comment by merks** [comment]
@akurtakov 

What's the strategy for updates during the RC1 phase?

## Minor Updates
 - [net.bytebuddy](https://repo1.maven.org/maven2/net/bytebuddy/)
    - [byte-buddy](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/) **[1.13.0](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.13.0)** < [1.14.0](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.14.0/)
    - [byte-buddy-agent](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/) **[1.13.0](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.13.0)** < [1.14.0](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.14.0/)
 - [org.jsoup](https://repo1.maven.org/maven2/org/jsoup/)
    - [jsoup](https://repo1.maven.org/maven2/org/jsoup/jsoup/) **[1.15.3](https://repo1.maven.org/maven2/org/jsoup/jsoup/1.15.3)** < [1.15.4](https://repo1.maven.org/maven2/org/jsoup/jsoup/1.15.4/)

**Comment by akurtakov** [comment]
When we update Orbit to final repo if there are updates we will push them so let's do these too. Assuming they don't require code changes.

**Comment by merks** [comment]
@akurtakov 

Jetty released a new version  yesterday


## Minor Updates
 - [org.eclipse.jetty](https://repo1.maven.org/maven2/org/eclipse/jetty/)
    - [apache-jsp](https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/10.0.14/)
    - [jetty-http](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.14/)
    - [jetty-io](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.14/)
    - [jetty-security](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.14/)
    - [jetty-server](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.14/)
    - [jetty-servlet](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.14/)
    - [jetty-util](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.14/)
    - [jetty-util-ajax](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/) **[10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.13)** < [10.0.14](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.14/)

So this update is available:

https://github.com/merks/simrel-maven/blob/main/platform/updated.target

But I assume the Platform is **not** updating this just before RC2, right?

**Comment by akurtakov** [comment]
That would have to wait.

**Comment by merks** [comment]
I see you've done jetty are and are working on these:

https://github.com/merks/simrel-maven/blob/main/platform/REPORT.md

**Comment by akurtakov** [comment]
Yeah, once approved legally I'll push them.
